version: '3'

services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
